apiVersion: batch/v1
kind: Job
metadata:
  name: poc-build-job
spec:
  template:
    spec:
      containers:
      - name: poc-build-job
        image: poc-build:0.1
        command: ["/bin/sh", "/apps/build.sh"]
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: pv-poc-storage
          mountPath: "/models"
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: pv-poc-storage
        persistentVolumeClaim:
          claimName: pv-poc-claim
      restartPolicy: Never