apiVersion: v1
kind: Namespace
metadata:
  name: poc
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: poc
  name: poc-account
secrets:
- name: poc-token
---
apiVersion: v1
kind: Secret
metadata:
  name: poc-token
  namespace: poc
  annotations:
    kubernetes.io/service-account.name: poc-account
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: poc-auth
  namespace: poc
rules:
- apiGroups: ["","apps","networking.k8s.io", "batch"]
  resources: ["pods","deployments","services","ingress","jobs"]
  # verbs: ["get","list","watch","create","update","patch","delete","edit"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: poc-auth-binding
  namespace: poc
subjects:
- kind: ServiceAccount
  name: poc-account
  namespace: poc
roleRef:
  kind: Role
  name: poc-auth
  apiGroup: rbac.authorization.k8s.io